name: Build & push

on:
  workflow_dispatch:

jobs:
  build-push-image:
    name: Build and Push Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          install: true

      - name: Login to DockerHub
        if: inputs.push-image
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}


      - name: Build image and push to Docker Hub
        id: docker_build
        uses: docker/build-push-action@v5
        with:
          # context: .
          # file: ${{ inputs.dockerfile }}
          tags: tferrari92/amd64-built-on-amd64:latest
          push: true
          # ssh: default
          platforms: linux/amd64
          # build-args: |
          #   PYTHON_VERSION=${{ env.PYTHON_VERSION }}
          # cache-from: type=gha
          # cache-to: type=gha,mode=max
